library(tweetscores)
library(tidyverse)

# R code to estimate all possible Twitter ideologies for a set of input accounts
# Each input account is assumed to have a file in followers/{id}.csv and following/{id}.csv
# which is generated by estimate_ideology.py
input <- "csmap-media.hydrated.tsv"
output <- "csmap-media.hydrated.ideology.tsv"

id_df <- read_tsv(input)
id_df$id <- sub("\\.\\d+$", "", id_df$id)
records <- data.frame(id = character(), followingMLE = double(), sdMLE = double(), followingCA = double())

for (id in id_df$id) {
    # followers <- read_csv(paste0("followers/", id, ".csv"))$id
    print(paste("calculating ideology for ", id))
    try({
        following <- read_csv(paste0("following/", id, ".csv"))$id

        # theta <- summary(estimateIdeology("", followers, method = "MLE")) %>%
        #    as_tibble() %>%
        #    select("mean") %>%
        #    tail(1) %>%
        #    .$mean
        # followersMLE <- c(theta, followersMLE)
        # followersCA <- c(estimateIdeology2("", followers))

        thetaMLE <- NA
        sdMLE <- NA
        try({
            result <- summary(estimateIdeology(id, following, method = "MLE")) %>%
                as_tibble() %>%
                select("mean", "sd") %>%
                tail(1)
            thetaMLE <- result$mean
            sdMLE <- result$sd
        })

        thetaCA <- NA
        try(
            thetaCA <- estimateIdeology2(id, following)
        )
        records <- records %>% add_row(id = id, followingMLE = thetaMLE, sdMLE = sdMLE, followingCA = thetaCA)
    })
}

records$sig <- records$sdMLE * 2 < abs(records$followingMLE)
records <- within(
    records,
    MLE_norm <- (followingMLE - mean(followingMLE, na.rm = TRUE)) / sd(followingMLE, na.rm = TRUE)
)


id_df %>%
    merge(records, by = "id") %>%
    write_tsv(output)