start:
	npm start

setup_node: install_nvm
	npm install

install_nvm:
	wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
	source ~/.bashrc
	nvm install v16.17.1

# you also need to set up lib/config.js
	
